name: Flutter CI/CD

on:
  push:
    tags:
      - "client-v*"
      - "admin-v*"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.4"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Determine flavor
        id: flavor
        run: |
          if [[ "${GITHUB_REF_NAME}" == client-* ]]; then
            echo "flavor=client" >> $GITHUB_OUTPUT
            echo "target=lib/main_client.dart" >> $GITHUB_OUTPUT
            echo "app_name=Smart Store Client" >> $GITHUB_OUTPUT
          else
            echo "flavor=admin" >> $GITHUB_OUTPUT
            echo "target=lib/main_admin.dart" >> $GITHUB_OUTPUT
            echo "app_name=Smart Store Admin" >> $GITHUB_OUTPUT
          fi

      - name: Build APK
        run: |
          flutter build apk \
            --release \
            --flavor ${{ steps.flavor.outputs.flavor }} \
            -t ${{ steps.flavor.outputs.target }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.flavor.outputs.app_name }} ${{ github.ref_name }}
          files: build/app/outputs/flutter-apk/app-${{ steps.flavor.outputs.flavor }}-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.flavor.outputs.app_name }}
          path: build/app/outputs/flutter-apk/app-${{ steps.flavor.outputs.flavor }}-release.apk
